name: heart_usb
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  get: 4.6.5
  http: ^0.13.4
  http_parser: ^4.0.1
  logger: ^1.1.0
  oktoast: ^3.2.0
  path_provider: ^2.0.11
  ripple_animation: ^0.0.1+2
  syncfusion_flutter_charts: ^20.2.36
  usb_serial: ^0.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
